---
pagetitle: Multiple random variables and their distributions
output: 
  revealjs::revealjs_presentation:
    incremental: false
    theme: solarized
    self_contained: false
    # reveal_plugins: ["menu","notes","chalkboard"]
    reveal_plugins: ["menu"]
    highlight: pygments
    center: true
    transition: none
    background_transition: none 
    reveal_options:
      # chalkboard:
      #   theme: whiteboard
      #   toggleNotesButton: true
      #   toggleChalkboardButton: true
      menu:
        numbers: true
      slideNumber: true
      previewLinks: false
    fig_caption: true
    css: mystyle.css
    
--- 

<section>

<h1>Multiple random variables and their distributions</h1>

Based on Stock and Watson, ch. 2

<br>

<h2>[Jesper Bagger](mailto:jesper.bagger@rhul.ac.uk)</h2>

<h3>EC2203 | Royal Holloway | 2020/21</h3>

</section>

# Multiple random variables and their distributions

## Joint distribution of discrete random variables

- The **joint probability mass function (PMF)** gives the probability that, **simultaneously**, $X=x$ and $Y=y$ 

  <div class="box">
  $$f_{XY}(x,y) = P(X=x,Y=y)$$
  </div>
  
- The **joint cumulative distribution function (CDF)** gives the probability that, **simultaneously**, $X \leq x$ and $Y \leq y$:

  <div class="box">
  $$F_{XY}(x,y) = P(X\leq x,Y \leq y)$$
  </div>


## Marginal distributions of discrete random variables

- The **marginal PMF** of $X$ is the probability that $X = x$, irrespective of the value of $Y$.

  <div class="box">
  $$f_X(x) = \sum_y f_{XY}(x,y)$$
  </div>  

- The marginal PMF of $Y$, $f_Y(y)$, is defined analogously

## Conditional PMF of discrete random variables

- The distribution of $Y$ given $X = x$ is the **conditional PMF** of $Y$ given $X$; the conditional PMF gives

  <div class="box">
  $$f_{Y|X}(y|x) = P(Y=y|X=x)$$
  </div>  


- $X$ is not random when $X = x$; it is a constant equal to $x$

- We obtain the conditional PMF $f_{Y|X}$ from $f_{XY}$ and $f_{X}$ as

  <div class="box">
  $$f_{Y|X}(y|x) = \frac{f_{XY}(x,y)}{f_{X}(x)}$$
  </div>  

## Joint distribution of continuous random variables

- As in the discrete case , the **joint CDF** gives the probability that, **simultaneously**, $X \leq x$ and $Y \leq y$; that is, 

  <div class="box">
  $$F_{XY}(x,y) = P(X\leq x,Y \leq y)$$
  </div> 
  
- The **joint probability density function (PDF)** is the derivative of the joint CDF

  <div class="box">
  $$f_{XY}(x,y) = \frac{\partial^2}{\partial x \partial y} F_{XY}(x,y)$$
  </div> 
  
## Marginal and conditional PDFs 

- The **marginal PDF** of $Y$ is

  <div class="box">
  $$f_Y(y) = \int_x f_{XY}(x,y) dx$$
  </div>


- The **conditional PDF** of $Y$ given $X=x$ is

  <div class="box">
  $$f_{Y|X}(y|x) = \frac{f_{XY}(x,y)}{f_X(x)}$$
  </div>

<!-- ## Interpreting the joint PDF of continuous random variables  -->

<!-- - The area under the **joint PDF** b/w any two sets of points---$a$ and $b$, and $c$ and $d$---gives the probability that $X$ falls b/w $a$ and $b$, and $Y$ falls b/w $c$ and $d$:  -->

<!--   $$\int_a^b \int_c^d f_{XY}(x,y) dx dy = P(a \leq X\leq b, c \leq Y \leq d)$$ -->

# Summary

## Summary

- The joint CDF of $X$ and $Y$ gives the probability that, simultaneously, $X \leq x$ and $Y \leq y$

- The joint PMF for discrete $X$ and $Y$ gives the probability that, simultaneously, $X=x$ and $Y=y$

- The marginal PMF of discrete $X$ is the PMF of $X$, irrespective of the value of $Y$

- The conditional PMF of discrete $Y$ given $X = x$ gives the PMF of $Y$ when $X = x$

- We can also define joint, marginal, and conditional PDFs for continuous random variables



